//! Wire protocol: generated protobuf types plus length-delimited framing.
//!
//! Unix sockets and SSH stdio carry the exact same stream:
//! `envelope_length:u32` in network byte order followed by one serialized
//! `WireEnvelope`. The framing stays transport-portable.

pub mod build_identity;
pub mod framing;
pub mod ids;

/// Generated protobuf types.
pub mod v1 {
    // Generated by prost from proto/farcooler.proto. Its enum layouts are
    // prost's business, not ours, and there is nothing to act on here.
    #![allow(clippy::large_enum_variant)]

    include!(concat!(env!("OUT_DIR"), "/farcooler.v1.rs"));
}

pub use v1::*;

/// Protocol major version this build speaks.
pub const PROTOCOL_VERSION: u32 = 1;

/// Which source this binary was built from: `0.1.0+a1b2c3d`, `-dirty` if the
/// worktree had uncommitted changes.
///
/// Reported by the daemon in every handshake and sent by every client in its
/// own, so that two components built from different source SAY so rather than
/// disagreeing silently — which is exactly how a fixed bug goes on reproducing.
/// `PROTOCOL_VERSION` answers "can these talk"; this answers "are these the
/// same build", and they are different questions.
pub const BUILD: &str = env!("FARCOOLER_BUILD");

/// Which installation this build belongs to.
///
/// Four channels are four separate installs that coexist on one host —
/// separate runtime directory, database, tmux server, binary name and bundle
/// identifier — so this is not a label. It decides where the daemon lives.
///
/// The names are the ones a developer tool audience already knows: `nightly`
/// and `canary` and `stable` mean the same things in Rust, Chrome and Zed as
/// they mean here.
///
/// Compile time, never a flag someone types. `scripts/version.sh` makes the
/// same call about the channel it derives: "a flag is a thing to forget on the
/// build that mattered." A daemon that could be told which channel it is could
/// be told wrong, and being wrong means a preview build writing into the stable
/// database.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Channel {
    /// Built on somebody's machine. Nothing is settled and nothing is promised.
    Local,
    /// Every push to `main`, published to internal testers automatically. The
    /// build that breaks first so the others do not.
    Canary,
    /// A `-preview.N` tag, for external testers.
    Preview,
    /// A release tag. What everyone else runs.
    Stable,
}

impl Channel {
    pub fn as_str(self) -> &'static str {
        match self {
            Channel::Local => "local",
            Channel::Canary => "canary",
            Channel::Preview => "preview",
            Channel::Stable => "stable",
        }
    }

    /// Anything unrecognized is `local`.
    ///
    /// The safe direction, and the reason it is worth stating: a local build
    /// isolates itself from everything, so guessing wrong costs a separate
    /// empty fleet. Guessing `stable` wrong costs someone else's.
    pub fn from_str_or_local(s: &str) -> Self {
        Self::from_str_or_local_const(s)
    }

    /// What this channel's daemon is called on disk.
    ///
    /// The SCHEME is frozen, not the literal: `farcoolerd[-<channel>]`. An App
    /// Store binary hardcodes the path it asks a runner for, which makes the
    /// shape of this name as public as any proto message — and stable's has no
    /// suffix precisely so that every client already in the field keeps
    /// resolving exactly what it always did.
    pub fn daemon_binary_name(self) -> &'static str {
        match self {
            Channel::Stable => "farcoolerd",
            Channel::Preview => "farcoolerd-preview",
            Channel::Canary => "farcoolerd-canary",
            Channel::Local => "farcoolerd-local",
        }
    }

    /// What this channel's CLI is called on disk. Same rule as the daemon's.
    pub fn cli_binary_name(self) -> &'static str {
        match self {
            Channel::Stable => "farcooler",
            Channel::Preview => "farcooler-preview",
            Channel::Canary => "farcooler-canary",
            Channel::Local => "farcooler-local",
        }
    }

    /// What this channel's tunnel helper is called on disk. Same rule as the
    /// daemon's.
    ///
    /// A Linux runner serves its tunnel from a separate process rather than
    /// from inside `farcoolerd`, because a Go c-archive linked into a musl
    /// binary segfaults in Go's runtime startup — see
    /// `crates/tailcat/go/exports_cgo.go` for the measurement. iOS and macOS
    /// link the archive and ship no helper at all, so this name only ever
    /// resolves to a file on Linux.
    ///
    /// Named here rather than next to the code that spawns it for the reason
    /// the daemon's own name is: four channels share one `~/.local/bin`, and a
    /// canary daemon must find the canary helper rather than whichever one an
    /// earlier stable install left behind.
    pub fn tunnel_binary_name(self) -> &'static str {
        match self {
            Channel::Stable => "farcooler-tunnel",
            Channel::Preview => "farcooler-tunnel-preview",
            Channel::Canary => "farcooler-tunnel-canary",
            Channel::Local => "farcooler-tunnel-local",
        }
    }

    /// The names this channel's daemon may go by on disk, most specific first.
    ///
    /// Two names, because two different things produce a Far Cooler binary and
    /// only one of them renames. `runner install` writes `daemon_binary_name()`
    /// on the destination, which is what lets four channels share one
    /// `~/.local/bin`. Cargo does not: `[[bin]] name = "farcoolerd"` is what
    /// comes out of `target/` no matter which channel stamped it, and
    /// `build-linux.sh`, `release.yml` and the macOS `build-app.sh` all copy
    /// that name along unchanged. Anything asking "where is the daemon that
    /// belongs to me" therefore has to accept both, or a checkout stops being
    /// able to run what it just built the moment it is not stable.
    ///
    /// The order is the safety property, not a preference: a directory holding
    /// both `farcoolerd` and `farcoolerd-preview` must answer a preview client
    /// with the preview daemon. Checking the bare name first would quietly
    /// hand it the stable one, which is the exact meeting these names exist to
    /// prevent.
    ///
    /// Use this to FIND a binary. Use `daemon_binary_name` to NAME one — an
    /// install has a single correct answer and no fallback.
    pub fn daemon_binary_candidates(self) -> &'static [&'static str] {
        match self {
            Channel::Stable => &["farcoolerd"],
            Channel::Preview => &["farcoolerd-preview", "farcoolerd"],
            Channel::Canary => &["farcoolerd-canary", "farcoolerd"],
            Channel::Local => &["farcoolerd-local", "farcoolerd"],
        }
    }

    /// The names this channel's CLI may go by on disk. Same rule as the
    /// daemon's.
    pub fn cli_binary_candidates(self) -> &'static [&'static str] {
        match self {
            Channel::Stable => &["farcooler"],
            Channel::Preview => &["farcooler-preview", "farcooler"],
            Channel::Canary => &["farcooler-canary", "farcooler"],
            Channel::Local => &["farcooler-local", "farcooler"],
        }
    }

    /// The names this channel's tunnel helper may go by on disk. Same rule as
    /// the daemon's.
    pub fn tunnel_binary_candidates(self) -> &'static [&'static str] {
        match self {
            Channel::Stable => &["farcooler-tunnel"],
            Channel::Preview => &["farcooler-tunnel-preview", "farcooler-tunnel"],
            Channel::Canary => &["farcooler-tunnel-canary", "farcooler-tunnel"],
            Channel::Local => &["farcooler-tunnel-local", "farcooler-tunnel"],
        }
    }

    /// The same rule in a form a `const` can call.
    ///
    /// `match` on a `&str` is not permitted in a const context, so this matches
    /// on bytes. One implementation with two entry points rather than two
    /// implementations: the round-trip test covers both.
    const fn from_str_or_local_const(s: &str) -> Self {
        match s.as_bytes() {
            b"stable" => Channel::Stable,
            b"preview" => Channel::Preview,
            b"canary" => Channel::Canary,
            _ => Channel::Local,
        }
    }
}

/// The channel this binary was built for, stamped by `build.rs`.
pub const CHANNEL: Channel = Channel::from_str_or_local_const(env!("FARCOOLER_CHANNEL"));

/// What a daemon can do, by name.
///
/// The mechanism that lets an app and a daemon drift apart, and the reason
/// `PROTOCOL_VERSION` above is expected never to move. A client that needs to
/// know whether a feature exists asks for it BY NAME rather than by comparing
/// version strings — no arithmetic, no compatibility matrix, and a name that
/// has shipped is permanent.
///
/// One table with three consumers: the daemon builds `ServerHello.capabilities`
/// and `DaemonVersion.capabilities` from it, and the CLI reports it. A second
/// copy is exactly the drift this exists to prevent.
///
/// Named per user-visible FEATURE, not per method. A client asks "does this
/// runner do stacks", never "does it implement stack.set_parent".
pub mod capability {
    /// Worktrees, repositories and roots. The floor: a daemon without this is
    /// not a daemon, and every build that has ever existed has it.
    ///
    /// The value keeps the old word, *workspace*: shipped clients ask for it
    /// by this name.
    pub const WORKTREES: &str = "workspaces";
    /// Workspaces as workstreams: `workspace.*`, `task.move`,
    /// `worktree.assign` and `terminal.set_role`, and the workspace fields on
    /// `Worktree`, `Terminal`, `Task`, `TaskChanged`, `TaskCreate`,
    /// `TaskListRequest` and `WorktreeCreate`.
    ///
    /// **Not `"workspaces"`.** That value is `WORKTREES` above: it named what
    /// is now called a worktree, every shipped client asks for it by that
    /// word, and every daemon that ever existed advertises it. Reusing it
    /// would have every runner in the field claim workspaces it does not have.
    /// So the new level takes a new word, `workstreams`, which is what the
    /// design calls a workspace.
    ///
    /// Its own capability for the reason every one below is its own, and
    /// several of its parts are FIELDS on existing payloads, which is the case
    /// `Request.required_capabilities` exists for: an older daemon drops
    /// `TaskCreate.workspace_id` and files the task on the only board it has.
    /// A client that sets one of those fields names this in the request.
    ///
    /// Absent means the runner has one board per repository and no
    /// workspaces, and a client draws no workspace level.
    pub const WORKSTREAMS: &str = "workstreams";
    /// Terminals, their screens and their input. Also the floor.
    pub const TERMINALS: &str = "terminals";
    /// Agent pane mode: the structured conversation, its prompts and its queue.
    pub const AGENT: &str = "agent";
    /// The review surface: change sets, diffs, commits, the inbox.
    pub const CHANGES: &str = "changes";
    /// Stacked branches and their pull requests.
    pub const STACK: &str = "stack";
    /// tmux tiling driven from a client.
    pub const LAYOUT: &str = "layout";
    /// Pasting a file into a terminal.
    pub const PASTE: &str = "paste";
    /// Reading and writing adapter configuration.
    pub const ADAPTERS: &str = "adapters";
    /// Themes and runner settings.
    pub const THEMES: &str = "themes";
    /// Reading, adding and removing the device keys in this runner's fence.
    ///
    /// Its own capability rather than part of `THEMES`: an app that cannot
    /// enroll on a runner has to say so before the ceremony starts, not after
    /// the user has scanned a code.
    pub const ENROLLMENT: &str = "enrollment";
    /// Telling a runner which terminals a client currently has on screen, so it
    /// can withhold a notification about an agent somebody is already looking
    /// at.
    ///
    /// Its own capability rather than part of `TERMINALS`, for the reason
    /// `ENROLLMENT` is its own: a daemon that predates this advertises
    /// `terminals` and cannot do it, so folding it in would have every runner
    /// claim a method half of them lack. The claim is a HEARTBEAT — every few
    /// seconds, for as long as a pane is on screen — so a client that could not
    /// tell would spend a failing round trip on that clock forever rather than
    /// once.
    ///
    /// Absent means the runner notifies exactly as it always did, which is why
    /// a client can simply not send it.
    pub const WATCHING: &str = "watching";
    /// Streaming a terminal's live bytes as a wire method: `terminal.attach`,
    /// answered with `Event.terminal_output` frames on the attaching
    /// connection.
    ///
    /// Its own capability rather than part of `TERMINALS`, for the reason
    /// `WATCHING` above is its own, and here it is load-bearing rather than
    /// tidy. Streaming has always been reachable — by exec'ing
    /// `farcoolerd --stream <id>` on a second ssh channel — so every daemon
    /// that ever shipped advertises `terminals` and cannot serve this method.
    /// A client that could not tell would have to try the attach and read the
    /// refusal, which costs a round trip on a runner where the exec still works
    /// perfectly well.
    ///
    /// Absent means the client execs `--stream` exactly as it always did, and
    /// falls back to polling if that stays silent. See
    /// `Session::open_stream` in `crates/client`.
    pub const TERMINAL_STREAM: &str = "terminal_stream";
    /// Registering a device's tailcat node key on this runner:
    /// `client.set_node_key`, answered with the runner's own connection token.
    ///
    /// Its own capability rather than part of `ENROLLMENT`, for the reason
    /// `WATCHING` and `TERMINAL_STREAM` above are their own: every daemon that
    /// ever shipped advertises `enrollment` and none of them before this one
    /// can serve this method. Folding it in would have every runner in the
    /// field claim a call half of them refuse — and the client asking is a
    /// device deciding whether it can reach this runner at all, which is a
    /// question it should be able to answer from the hello rather than from a
    /// failed round trip.
    ///
    /// Absent means the runner has no tunnel to be admitted to, so the client
    /// keeps reaching it by address exactly as it always did.
    pub const TUNNEL: &str = "tunnel";
    /// Dragging worktrees into an order and having the runner keep it:
    /// `worktree.reorder`, and the `Worktree.ordinal` that comes back.
    ///
    /// Its own capability rather than part of `WORKTREES`, for the reason
    /// `WATCHING`, `TERMINAL_STREAM` and `TUNNEL` above are their own — and
    /// here the silence it prevents is the quietest of the four. `workspaces`
    /// is the floor: every daemon that has ever existed advertises it, and none
    /// before this one stores a rank. A client that folded this in would draw
    /// drag handles against an older runner, let somebody rearrange their
    /// sidebar, and put it all back on the next refresh with no error anywhere.
    ///
    /// Absent means the runner has no order to keep, so a client leaves the
    /// list where the daemon put it and offers no handles.
    ///
    /// The value keeps the old word, *workspace*: shipped clients ask for it
    /// by this name.
    pub const WORKTREE_ORDER: &str = "workspace_order";
    /// The repository task board: `task.list` through `task.search`, and the
    /// `task_changed` event that says one of them moved.
    ///
    /// Its own capability rather than part of `WORKTREES`, for the reason
    /// every one above it is its own. `workspaces` is the floor — every daemon
    /// that has ever existed advertises it and none before this one has a
    /// board — so a client that folded this in would draw a board against an
    /// older runner and get `CAPABILITY_UNSUPPORTED` for every read behind it,
    /// which is an empty board with no explanation rather than a surface it
    /// knew not to offer.
    ///
    /// Absent means the runner keeps no tasks, and a client offers no board
    /// for it. The Mac's sidebar draws its Board row only where the runner
    /// advertises this; the phone draws its overview's Board rows on the same
    /// terms; and `crates/client`'s `task.list` and `task.get` refuse without a
    /// round trip on a runner that does not, with the code the daemon itself
    /// would answer.
    ///
    /// The daemon still routes every `task.*` method through this capability
    /// and answers `CAPABILITY_UNSUPPORTED`, which is what a person meets by
    /// any path that does not ask first: the CLI turns it into its own
    /// sentence, and the Mac's ⇧⌘B, which is not gated, reports a board it
    /// could not read.
    pub const TASKS: &str = "tasks";
    /// `TerminalCreate.prompt`: an agent terminal that starts on a message,
    /// passed as the agent's launch argument.
    ///
    /// A FIELD rather than a method, which is exactly the case
    /// `Request.required_capabilities` exists for: an older daemon drops the
    /// field as unknown and opens the agent with an empty composer, with no
    /// error anywhere. A client that sends a prompt names this in the request,
    /// and a client that reads it absent types the message in itself, as it
    /// always did.
    pub const LAUNCH_PROMPT: &str = "launch_prompt";
    /// `TerminalCreate.task_key`: a terminal opened for a board task, which
    /// exports `FARCOOLER_TASK` and starts its agent on the task.
    ///
    /// A field, so its own capability, for `LAUNCH_PROMPT`'s reason: an older
    /// daemon drops it without a word, and `farcooler task dispatch` would
    /// then move a task into progress beside a pane that was never told
    /// about it. A client that sends one names this in the request.
    pub const TERMINAL_TASK: &str = "terminal_task";
    /// `WorktreeCreate.fork_only`: a create that makes a new branch or
    /// refuses, never checking out one a remote already has.
    ///
    /// A field, so its own capability, for `LAUNCH_PROMPT`'s reason: an older
    /// daemon drops it without a word and checks a remote-only name out,
    /// which starts a new task on somebody else's commits. A client that
    /// sets it names this in the request, and a client that reads it absent
    /// keeps its own check against the branch list.
    ///
    /// The value keeps the old word, *workspace*: shipped clients ask for it
    /// by this name.
    pub const WORKTREE_FORK_ONLY: &str = "workspace_fork_only";
    /// `WorkspaceStartOrchestrator.handoff_task`: a new orchestrator told to
    /// read a task's handoff note first (`--read`).
    ///
    /// A field, so its own capability, for `LAUNCH_PROMPT`'s reason: an older
    /// daemon drops it without a word and starts an orchestrator that never
    /// hears where the split left its handoff. A client that sends one names
    /// this in the request.
    pub const ORCHESTRATOR_HANDOFF: &str = "orchestrator_handoff";
    /// The needs-you rollup: `needs_you.list`, the `needs_you_changed`
    /// event, and `Worktree.open_tasks`.
    ///
    /// Its own capability for `WATCHING`'s reason: every daemon before this
    /// one advertises `terminals` and `tasks` and cannot serve the list. A
    /// client that reads it absent derives blocked items from
    /// `Terminal.activity` and says the runner needs an update to show asks
    /// and decisions.
    pub const NEEDS_YOU: &str = "needs_you";
    /// Answering a decision tells the agent waiting on it:
    /// `workspace.set_settings` and `Workspace.wake_on_answer`.
    ///
    /// Its own capability because an older daemon has neither the switch nor
    /// the behavior: a client that reads it absent draws no switch rather
    /// than one that changes nothing.
    pub const WAKE_ON_ANSWER: &str = "wake_on_answer";
    /// How a board lands its work (ov-313): `Workspace.landing`, `base`,
    /// `budget_lines`, `pr_cost_line` and `direct_refused`, their writes on
    /// `workspace.set_settings`, and `repository.landing`.
    ///
    /// Its own capability because an older daemon has none of it and drops the
    /// fields of a settings write it does not know: a client that sets one
    /// names this in the request, and one that reads it absent draws no
    /// landing setting rather than one that changes nothing.
    pub const LANDING: &str = "landing";
    /// `farcooler terminal stream --sizes`: a pane's byte stream carrying
    /// the pane's size, `ESC P > farcooler-size;<columns>;<rows> ESC \`, ahead
    /// of the first bytes written at each new size — and the promise that
    /// every marker shaped like that in the stream is the runner's, because
    /// the runner removes any a program prints.
    ///
    /// Its own capability because a client has to know both halves before it
    /// may act on one: a runner before this rejects the flag outright, and a
    /// marker from a stream without the promise is just bytes somebody
    /// printed. A client that reads it absent opens streams without the flag
    /// and sizes its emulator from layout replies, as it always did.
    pub const STREAM_SIZE_MARKERS: &str = "stream_size_markers";
    /// Task notices (ov-94): the `notice` event, `Host.push_paired`, and an
    /// agent working on a task notifying through its task's notice.
    ///
    /// Its own capability because a client that posts its own banners (the
    /// Mac) leaves a task-bound agent's banner to the task's notice only when
    /// the runner sends one; on an older runner it posts as it always has.
    pub const TASK_NOTICES: &str = "task_notices";
    /// `report.get`: what got done in a period, from the board's record.
    ///
    /// Its own capability because no runner before this one can compute
    /// it: a client that reads it absent says the runner needs an update.
    pub const REPORT: &str = "report";
    /// What agents spent (ov-194): `usage.report` and `usage.task`.
    ///
    /// Its own capability because no daemon before this one records it: a
    /// client that reads it absent says the runner needs an update to report
    /// spend, rather than showing zero.
    pub const AGENT_USAGE: &str = "agent_usage";
    /// `Host.agents_found`: which of `claude`, `codex` and `cursor-agent` the
    /// runner's user can run (ov-205).
    ///
    /// Its own capability because the field is a repeated one, and an older
    /// runner's absent list decodes as an empty one. Without this a client
    /// would read every runner from before it as having no agents and grey
    /// out Start Orchestrator on a runner that can start one. A client that
    /// reads it absent offers every agent, as it always did.
    pub const AGENTS_FOUND: &str = "agents_found";
    /// When a task will start (ov-212): `task.set_wait`, `task.set_line`,
    /// and `Task.wait` and `Task.waiting_on`.
    ///
    /// Its own capability because an older runner drops the fields: a CLI
    /// that reads it absent refuses before sending, saying the runner needs
    /// an update to record when a task starts.
    pub const TASK_WAITS: &str = "task_waits";
    /// Subagents as task workers (ov-213): `task.worker` and `Task.workers`.
    ///
    /// Apart from `TASK_WAITS` so either half can ship alone. A CLI that
    /// reads it absent says the runner needs an update to record subagents;
    /// an app keeps its old "No Agent" rule.
    pub const TASK_WORKERS: &str = "task_workers";
    /// `Terminal.notice_task_id` (ov-112): the task a terminal's own
    /// notifications fold into, decided by the runner.
    ///
    /// Its own capability because an absent field means both "notifies as
    /// itself" and "a runner too old to say". A client that reads the
    /// capability absent folds nothing, which at worst shows a duplicate banner
    /// and never silences one.
    pub const NOTICE_TASK: &str = "notice_task";
    /// Read state on the runner (ov-113): `workspace.mark_read`,
    /// `TaskList.reads` and the `board_reads_changed` event.
    ///
    /// Its own capability because an older runner drops the write and sends no
    /// state: a client that reads it absent keeps its own per-device store.
    /// Needs `workstreams`, since a board here is a workspace's.
    pub const BOARD_READS: &str = "board_reads";
    /// A worktree's files, read-only (ov-189): `worktree.list_dir` and
    /// `worktree.read_file`.
    ///
    /// Its own capability because no runner before this one can answer
    /// either: a client that reads it absent says the runner needs an update
    /// to show files, rather than an empty tree.
    pub const WORKTREE_FILES: &str = "worktree_files";
    /// Naming a terminal (ov-234): `terminal.rename`.
    ///
    /// Its own capability because an older runner has no such method: a
    /// client that reads it absent hides Rename rather than offering a menu
    /// item that can only fail.
    pub const TERMINAL_NAMES: &str = "terminal_names";
    /// `Terminal.ports` (ov-234): the TCP ports a terminal is listening on, as
    /// a field rather than text inside its name.
    ///
    /// Apart from `TERMINAL_NAMES` so either half can ship alone. Its own
    /// capability because an older runner drops the field, and its absent list
    /// would read as "nothing is listening" on a runner that may well be
    /// serving: a client that reads it absent keeps the `web :PORT` text the
    /// name already carried and offers no Open in Browser.
    pub const TERMINAL_PORTS: &str = "terminal_ports";
    /// Extra read-only folders for the file viewer (ov-232):
    /// `Host.read_only_folders`, and `folder` on `worktree.list_dir` and
    /// `worktree.read_file`.
    ///
    /// Its own capability because an older runner drops the field and sends
    /// no list: a client that reads it absent shows no folders, and one that
    /// asks for a folder names this in the request, so an older runner
    /// refuses rather than answering from no worktree.
    pub const READ_ONLY_FOLDERS: &str = "read_only_folders";
    /// Editing, cancelling and sending now a queued agent prompt (ov-171):
    /// `terminal.agent_edit_queued`, `terminal.agent_cancel_queued` and
    /// `terminal.agent_steer_queued`.
    ///
    /// Its own capability because a runner from before the queue's controls
    /// advertises `agent` and refuses all three as an unknown method, so
    /// `agent` could not say whether Edit, Cancel and Send Now would work. A
    /// client that reads it absent says the runner needs an update to manage
    /// queued messages, rather than offering controls that can only fail.
    pub const AGENT_QUEUE: &str = "agent_queue";
    /// The plan layer (ov-268): `plan.get`, `plan.set`, `plan.events`,
    /// `board_theme.*`, `lane.*` and the `plan_changed` event.
    ///
    /// **Experimental, and it may be withdrawn.** Themes, lanes and the plan
    /// sit beside the board, never in it: no task carries a field of the layer,
    /// so removing it changes nothing a task says. Its own capability because
    /// no runner before this one has any of the methods: a client that reads it
    /// absent hides the Plan view and a CLI refuses before sending, saying the
    /// runner needs an update to keep a plan. Needs `workstreams`, since a board
    /// here is a workspace's.
    pub const BOARD_PLAN: &str = "board_plan";
    /// A worktree says when large files weren't downloaded (ov-199):
    /// `Worktree.lfs_pointers`, and `worktree.hydrate_lfs` to try again.
    ///
    /// Its own capability for `WORKTREE_ORDER`'s reason: the field is dropped
    /// by an older daemon without a word, and the method refused as an unknown
    /// one. A client that reads it absent shows no notice and no button.
    pub const LFS_POINTERS: &str = "lfs_pointers";
    /// Orchestrator pages (ov-269): `page.list`, `page.get`, `page.set`,
    /// `page.remove`, `page.stats` and the `pages_changed` event.
    ///
    /// **Experimental, and it may be withdrawn.** A page is a document of typed
    /// blocks an orchestrator publishes and the apps draw natively. Pages sit
    /// beside the board, never in it: no task and nothing in the plan layer
    /// refers to one, and a page names cards, lanes and themes by text, so it
    /// needs `workstreams` (a board here is a workspace's) and nothing else. In
    /// particular it doesn't need `board_plan`: with the plan layer removed a
    /// page still draws, its lane and theme references as plain text. A client
    /// that reads it absent hides pages, and a CLI refuses before sending,
    /// saying the runner needs an update to show pages.
    pub const BOARD_PAGES: &str = "board_pages";
    /// Decided for you (ov-304): `ruling.add`, `ruling.set`, and
    /// `Plan.rulings` on `plan.get`.
    ///
    /// **Experimental, with the plan layer it is part of.** A ruling is a
    /// reversible call the orchestrator made for the owner. Its own capability
    /// because a runner with `board_plan` alone has none: a client that reads
    /// it absent shows no Decided For You section, and a CLI refuses a ruling
    /// verb before sending, saying the runner needs an update to keep rulings.
    /// Needs `board_plan`, since rulings are read through the plan.
    pub const BOARD_RULINGS: &str = "board_rulings";
    /// The owner keeps or reverses a ruling (ov-333): `ruling.keep_all`,
    /// `RulingSet.sha` and `BoardRuling.reversed_sha`.
    ///
    /// Its own capability because a runner with `board_rulings` alone drops
    /// the new fields without a word and refuses the method as an unknown
    /// one. A client that reads it absent offers no Keep, Keep All or
    /// Reverse, and a CLI refuses the verbs before sending. Needs
    /// `board_rulings`.
    pub const BOARD_RULING_ACTIONS: &str = "board_ruling_actions";
    /// Trains (ov-309): `train.start`, `train.set`, and `Plan.trains` and
    /// `Plan.ci` on `plan.get`, with the runner reading each pushed SHA's CI
    /// through `gh`.
    ///
    /// **Experimental, with the plan layer it is part of.** Its own capability
    /// because a runner with `board_plan` alone keeps no trains: a client that
    /// reads it absent draws Now without train groups and a page's CI
    /// references as plain text, and a CLI refuses a train verb before
    /// sending, saying the runner needs an update to keep trains. Needs
    /// `board_plan`, since trains are read through the plan.
    pub const BOARD_TRAINS: &str = "board_trains";
    /// Cost on the plan (ov-307): `budget_tokens` on `board_theme.update` and
    /// `lane.update` and on the theme and lane in `plan.get`, a theme's
    /// seven-day trend, and `Plan.cost` with the week's tokens and cost per
    /// finished card by harness and model.
    ///
    /// **Experimental, with the plan layer it is part of.** No method of its
    /// own, since budgets ride the two updates. A client that reads it absent
    /// draws no budgets, trend or comparison, and a CLI refuses `--budget`
    /// before sending, saying the runner needs an update to keep budgets.
    /// Needs `board_plan`, since it is read through the plan.
    pub const BOARD_COST: &str = "board_cost";
    /// Agent rows (ov-366): `agent.rows` and `agent.rows_follow`, a page of a
    /// terminal's projected agent rows and a follow of them by revision.
    ///
    /// **Experimental, behind the runner's `FARCOOLER_PROJECTOR=1`** until a
    /// client reads it (ov-372): without it both methods are refused as
    /// unsupported. Its own capability because no earlier runner has either.
    pub const AGENT_ROWS: &str = "agent_rows";
    /// A draft held behind a dialog (ov-385): `hold_behind_dialog` on
    /// `terminal.draft_prompt`, the `DraftHold` it answers with,
    /// `Terminal.draft_hold` and `terminal.draft_withdraw`.
    ///
    /// Its own capability because an older runner drops the flag and refuses
    /// a draft a dialog is in the way of: a client that reads it absent copies
    /// the draft to the clipboard instead, as it always did.
    pub const DRAFT_HOLD: &str = "draft_hold";
    /// `settings.set_projector` (ov-372): turn the runner's projector, and so
    /// `agent_rows`, on or off from a client's settings, without a restart.
    pub const PROJECTOR_SETTING: &str = "projector_setting";
    /// `terminal.compose` (ov-372): the native view's send. Its own word, so
    /// a runner that serves rows from before compose isn't offered a view
    /// whose send would fail.
    pub const AGENT_COMPOSE: &str = "agent_compose";
    /// `terminal.compose` takes line breaks, images and slash commands, and answers once claude
    /// confirms (ov-367); with `agent_compose` alone, one line and no image.
    pub const COMPOSE: &str = "compose";

    /// Every capability this build has, in a stable order.
    ///
    /// Stable so that two daemons of the same build produce byte-identical
    /// hellos, which makes the list diffable in a log.
    pub const ALL: &[&str] =
        &[
            WORKTREES, TERMINALS, AGENT, CHANGES, STACK, LAYOUT, PASTE, ADAPTERS, THEMES,
            ENROLLMENT, WATCHING, TERMINAL_STREAM, TUNNEL, WORKTREE_ORDER, TASKS,
            LAUNCH_PROMPT, TERMINAL_TASK, WORKTREE_FORK_ONLY, WORKSTREAMS, ORCHESTRATOR_HANDOFF,
            NEEDS_YOU, WAKE_ON_ANSWER, STREAM_SIZE_MARKERS, TASK_NOTICES, REPORT, AGENT_USAGE,
            AGENTS_FOUND,
            TASK_WAITS, TASK_WORKERS, NOTICE_TASK, BOARD_READS, WORKTREE_FILES, TERMINAL_NAMES, TERMINAL_PORTS,
            READ_ONLY_FOLDERS, AGENT_QUEUE, BOARD_PLAN, LFS_POINTERS, BOARD_PAGES, BOARD_RULINGS,
            BOARD_TRAINS, BOARD_COST, LANDING, BOARD_RULING_ACTIONS, AGENT_ROWS, DRAFT_HOLD,
            PROJECTOR_SETTING, AGENT_COMPOSE,
            COMPOSE,
        ];

    /// Capabilities this process has but does not offer: a feature behind a
    /// runner's flag (`agent_rows` with the projector off). Set at start, and
    /// again when `settings.set_projector` turns it on or off.
    static WITHHELD: std::sync::RwLock<Vec<&'static str>> = std::sync::RwLock::new(Vec::new());

    /// Stop offering `capability`, in the hello and in `daemon.version`.
    pub fn withhold(capability: &'static str) {
        let mut withheld = WITHHELD.write().unwrap_or_else(|e| e.into_inner());
        if !withheld.contains(&capability) {
            withheld.push(capability);
        }
    }

    /// Offer `capability` again (`settings.set_projector` turning it on).
    pub fn offer(capability: &str) {
        WITHHELD.write().unwrap_or_else(|e| e.into_inner()).retain(|c| *c != capability);
    }

    /// What this process offers: `ALL`, less what it withholds.
    pub fn advertised() -> Vec<String> {
        let withheld = WITHHELD.read().unwrap_or_else(|e| e.into_inner());
        ALL.iter().filter(|c| !withheld.contains(c)).map(|c| (*c).to_string()).collect()
    }

    /// The capability a method belongs to, or `None` if there is no such
    /// method.
    ///
    /// Read off `method::Method`, the one table of methods, so a method and its
    /// capability are declared on one line and cannot be added apart.
    pub fn for_method(method: &str) -> Option<&'static str> {
        super::method::Method::parse(method).map(super::method::Method::capability)
    }
}

/// Every method the wire carries, in one table.
///
/// The one list every other list is derived from. It used to be four: this
/// crate's capability match, the daemon's scope match, the daemon's dispatch
/// and the FFI's dispatch, each typed by hand. They drifted. The daemon
/// refused Edit, Cancel and Send Now on a queued agent message as a method it
/// had never heard of, because its scope match stopped one row short of this
/// crate's, and the FFI never routed the model and config pickers at all.
///
/// So the other tables are matches on `Method` with no wildcard: the daemon's
/// scope (`rpc::scope_of`) and the FFI's route (`ffi::route`). A row added
/// here is a compile error in each until it has been given a scope and a route,
/// and the tests that enumerate `Method::ALL` cover what the compiler cannot,
/// that the daemon dispatches it and the FFI's arm exists.
pub mod method {
    /// Declares `Method` and everything read straight off its row.
    macro_rules! methods {
        ($($variant:ident = $name:literal => $capability:ident,)*) => {
            /// A method by its wire name. See the module.
            #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
            pub enum Method {
                $($variant,)*
            }

            impl Method {
                /// Every method, in the table's order.
                pub const ALL: &'static [Method] = &[$(Method::$variant,)*];

                /// The name on the wire, `Request.method`.
                pub fn name(self) -> &'static str {
                    match self {
                        $(Method::$variant => $name,)*
                    }
                }

                /// The capability a client asks for before calling it.
                pub fn capability(self) -> &'static str {
                    match self {
                        $(Method::$variant => super::capability::$capability,)*
                    }
                }

                /// The method a wire name names, or `None` for one this build
                /// has never heard of. Exact: no prefix and no fuzzy match.
                pub fn parse(name: &str) -> Option<Method> {
                    match name {
                        $($name => Some(Method::$variant),)*
                        _ => None,
                    }
                }
            }
        };
    }

    methods! {
        HostGet = "host.get" => WORKTREES,
        HostHealth = "host.health" => WORKTREES,
        DaemonVersion = "daemon.version" => WORKTREES,
        DaemonShutdown = "daemon.shutdown" => WORKTREES,
        RepositoryList = "repository.list" => WORKTREES,
        RepositoryRegister = "repository.register" => WORKTREES,
        RepositoryRootList = "repository_root.list" => WORKTREES,
        RepositoryRootAdd = "repository_root.add" => WORKTREES,
        RepositoryRootRemove = "repository_root.remove" => WORKTREES,
        WorktreeList = "worktree.list" => WORKTREES,
        WorktreeCreate = "worktree.create" => WORKTREES,
        WorktreeHide = "worktree.hide" => WORKTREES,
        WorktreeUnhide = "worktree.unhide" => WORKTREES,
        WorktreeRemove = "worktree.remove" => WORKTREES,
        BranchList = "branch.list" => WORKTREES,
        WorktreeDiscover = "worktree.discover" => WORKTREES,
        WorktreeFileSearch = "worktree.file_search" => WORKTREES,
        TerminalList = "terminal.list" => TERMINALS,
        TerminalCreate = "terminal.create" => TERMINALS,
        TerminalScreen = "terminal.screen" => TERMINALS,
        TerminalWrite = "terminal.write" => TERMINALS,
        TerminalResize = "terminal.resize" => TERMINALS,
        TerminalStop = "terminal.stop" => TERMINALS,
        TerminalSeen = "terminal.seen" => TERMINALS,
        TerminalRemove = "terminal.remove" => TERMINALS,
        TerminalDismissLost = "terminal.dismiss_lost" => TERMINALS,
        TerminalRestart = "terminal.restart" => TERMINALS,
        TerminalPasteFile = "terminal.paste_file" => PASTE,
        TerminalSetPaneMode = "terminal.set_pane_mode" => AGENT,
        TerminalAgentSubscribe = "terminal.agent_subscribe" => AGENT,
        TerminalAgentPrompt = "terminal.agent_prompt" => AGENT,
        TerminalDraftPrompt = "terminal.draft_prompt" => AGENT,
        TerminalTell = "terminal.tell" => AGENT,
        TerminalDraftWithdraw = "terminal.draft_withdraw" => DRAFT_HOLD,
        TerminalCompose = "terminal.compose" => AGENT_COMPOSE,
        TerminalAgentAnswer = "terminal.agent_answer" => AGENT,
        TerminalAgentSetMode = "terminal.agent_set_mode" => AGENT,
        TerminalAgentSetModel = "terminal.agent_set_model" => AGENT,
        TerminalAgentSetConfig = "terminal.agent_set_config" => AGENT,
        TerminalAgentEditQueued = "terminal.agent_edit_queued" => AGENT_QUEUE,
        TerminalAgentCancelQueued = "terminal.agent_cancel_queued" => AGENT_QUEUE,
        TerminalAgentSteerQueued = "terminal.agent_steer_queued" => AGENT_QUEUE,
        TerminalAgentCancel = "terminal.agent_cancel" => AGENT,
        ChangesChangeSet = "changes.change_set" => CHANGES,
        ChangesCommitFiles = "changes.commit_files" => CHANGES,
        ChangesFileDiff = "changes.file_diff" => CHANGES,
        ChangesSetBase = "changes.set_base" => CHANGES,
        ChangesMarkRead = "changes.mark_read" => CHANGES,
        ChangesInbox = "changes.inbox" => CHANGES,
        StackGet = "stack.get" => STACK,
        StackSetParent = "stack.set_parent" => STACK,
        PrRefresh = "pr.refresh" => STACK,
        LayoutList = "layout.list" => LAYOUT,
        LayoutSplit = "layout.split" => LAYOUT,
        LayoutMove = "layout.move" => LAYOUT,
        LayoutResize = "layout.resize" => LAYOUT,
        LayoutBreak = "layout.break" => LAYOUT,
        LayoutRename = "layout.rename" => LAYOUT,
        LayoutViewport = "layout.viewport" => LAYOUT,
        LayoutPreset = "layout.preset" => LAYOUT,
        LayoutCycle = "layout.cycle" => LAYOUT,
        LayoutFocus = "layout.focus" => LAYOUT,
        LayoutZoom = "layout.zoom" => LAYOUT,
        LayoutSwap = "layout.swap" => LAYOUT,
        LayoutGroupSelect = "layout.group.select" => LAYOUT,
        AdapterList = "adapter.list" => ADAPTERS,
        AdapterUpsert = "adapter.upsert" => ADAPTERS,
        AdapterDelete = "adapter.delete" => ADAPTERS,
        AdapterTest = "adapter.test" => ADAPTERS,
        ThemeList = "theme.list" => THEMES,
        ThemeUpsert = "theme.upsert" => THEMES,
        ThemeDelete = "theme.delete" => THEMES,
        SettingsSetBranchPrefix = "settings.set_branch_prefix" => THEMES,
        SettingsSetProjector = "settings.set_projector" => PROJECTOR_SETTING,
        ClientList = "client.list" => ENROLLMENT,
        ClientEnroll = "client.enroll" => ENROLLMENT,
        ClientRevoke = "client.revoke" => ENROLLMENT,
        ClientSetNodeKey = "client.set_node_key" => TUNNEL,
        WorktreeReorder = "worktree.reorder" => WORKTREE_ORDER,
        WorktreeHydrateLfs = "worktree.hydrate_lfs" => LFS_POINTERS,
        TaskList = "task.list" => TASKS,
        TaskGet = "task.get" => TASKS,
        TaskGetByKey = "task.get_by_key" => TASKS,
        TaskCreate = "task.create" => TASKS,
        TaskUpdate = "task.update" => TASKS,
        TaskSetStatus = "task.set_status" => TASKS,
        TaskNote = "task.note" => TASKS,
        TaskBlock = "task.block" => TASKS,
        TaskSearch = "task.search" => TASKS,
        WorkspaceList = "workspace.list" => WORKSTREAMS,
        WorkspaceCreate = "workspace.create" => WORKSTREAMS,
        WorkspaceRename = "workspace.rename" => WORKSTREAMS,
        WorkspaceSetPrefix = "workspace.set_prefix" => WORKSTREAMS,
        WorkspaceDelete = "workspace.delete" => WORKSTREAMS,
        TaskMove = "task.move" => WORKSTREAMS,
        WorktreeAssign = "worktree.assign" => WORKSTREAMS,
        TerminalSetRole = "terminal.set_role" => WORKSTREAMS,
        WorkspaceStartOrchestrator = "workspace.start_orchestrator" => WORKSTREAMS,
        TerminalWatching = "terminal.watching" => WATCHING,
        TerminalAttach = "terminal.attach" => TERMINAL_STREAM,
        NeedsYouList = "needs_you.list" => NEEDS_YOU,
        WorkspaceSetSettings = "workspace.set_settings" => WAKE_ON_ANSWER,
        ReportGet = "report.get" => REPORT,
        UsageReport = "usage.report" => AGENT_USAGE,
        UsageTask = "usage.task" => AGENT_USAGE,
        TaskSetWait = "task.set_wait" => TASK_WAITS,
        TaskSetLine = "task.set_line" => TASK_WAITS,
        TaskWorker = "task.worker" => TASK_WORKERS,
        WorkspaceMarkRead = "workspace.mark_read" => BOARD_READS,
        WorktreeListDir = "worktree.list_dir" => WORKTREE_FILES,
        WorktreeReadFile = "worktree.read_file" => WORKTREE_FILES,
        TerminalRename = "terminal.rename" => TERMINAL_NAMES,
        PlanGet = "plan.get" => BOARD_PLAN,
        PlanSet = "plan.set" => BOARD_PLAN,
        PlanEvents = "plan.events" => BOARD_PLAN,
        BoardThemeCreate = "board_theme.create" => BOARD_PLAN,
        BoardThemeUpdate = "board_theme.update" => BOARD_PLAN,
        BoardThemeCards = "board_theme.cards" => BOARD_PLAN,
        LaneCreate = "lane.create" => BOARD_PLAN,
        LaneUpdate = "lane.update" => BOARD_PLAN,
        LaneCards = "lane.cards" => BOARD_PLAN,
        LaneAgent = "lane.agent" => BOARD_PLAN,
        PageList = "page.list" => BOARD_PAGES,
        PageGet = "page.get" => BOARD_PAGES,
        PageSet = "page.set" => BOARD_PAGES,
        PageRemove = "page.remove" => BOARD_PAGES,
        PageStats = "page.stats" => BOARD_PAGES,
        RulingAdd = "ruling.add" => BOARD_RULINGS,
        RulingSet = "ruling.set" => BOARD_RULINGS,
        RulingKeepAll = "ruling.keep_all" => BOARD_RULING_ACTIONS,
        TrainStart = "train.start" => BOARD_TRAINS,
        TrainSet = "train.set" => BOARD_TRAINS,
        RepositoryLanding = "repository.landing" => LANDING,
        AgentRows = "agent.rows" => AGENT_ROWS,
        AgentRowsFollow = "agent.rows_follow" => AGENT_ROWS,
    }
}

/// Control envelopes are capped at 1 MiB.
pub const MAX_CONTROL_ENVELOPE_BYTES: usize = 1024 * 1024;

/// The most image bytes one `terminal.compose` carries, all its images
/// together: under the envelope's 1 MiB, with room for the text (ov-367).
pub const MAX_COMPOSE_IMAGE_BYTES: usize = 900 * 1024;

/// `TerminalFrame.payload` is capped at 64 KiB.
pub const MAX_TERMINAL_PAYLOAD_BYTES: usize = 64 * 1024;

/// One chunk of a file being pasted into a terminal.
///
/// Twice a terminal frame and an eighth of the envelope ceiling: big enough
/// that a 16 MiB file is 128 round trips rather than a thousand, small enough
/// that live output interleaves between chunks instead of waiting behind one.
pub const PASTE_CHUNK_BYTES: usize = 128 * 1024;

/// The largest file a client may paste into a terminal.
///
/// Larger than any screenshot or ordinary document, and small enough that a
/// failed transfer costs seconds rather than minutes. Checked on both sides:
/// the client refuses before uploading anything, the daemon before writing it.
pub const MAX_PASTE_FILE_BYTES: u64 = 16 * 1024 * 1024;

/// Each terminal retains the most recent 8 MiB of its current epoch.
pub const REPLAY_BUFFER_BYTES: u64 = 8 * 1024 * 1024;

/// Per-client terminal output window: unacknowledged data cap.
pub const MAX_UNACKED_TERMINAL_BYTES: u64 = 1024 * 1024;

/// Control channel ceiling: queued unwritten control envelopes per client.
pub const MAX_QUEUED_CONTROL_BYTES: u64 = 4 * 1024 * 1024;

/// Clients acknowledge at 256 KiB unacknowledged or 250 ms, whichever first,
/// and always within 1 s of output that leaves anything unacknowledged.
pub const FLOW_ACK_BYTES_THRESHOLD: u64 = 256 * 1024;
pub const FLOW_ACK_INTERVAL_MS: u64 = 250;
pub const FLOW_ACK_MAX_DELAY_MS: u64 = 1000;

/// A disconnected writer lease expires after 30 seconds.
pub const WRITER_LEASE_EXPIRY_SECS: u64 = 30;

/// Terminal dimensions are clamped to these ranges.
pub const MIN_COLUMNS: u32 = 20;
pub const MAX_COLUMNS: u32 = 500;
pub const MIN_ROWS: u32 = 5;
pub const MAX_ROWS: u32 = 200;

#[cfg(test)]
mod board_reads_tests;
#[cfg(test)]
mod page_wire_tests;
#[cfg(test)]
mod plan_layer_tests;
#[cfg(test)]
mod ruling_wire_tests;
#[cfg(test)]
mod capability_tests;
#[cfg(test)]
mod train_wire_tests;
#[cfg(test)]
mod cost_wire_tests;
#[cfg(test)]
mod task_starts_tests;

#[cfg(test)]
mod tests {
    use super::*;

    /// `TaskBlockSet.reason` carries presence, and the bytes have to agree
    /// with what its comment in the proto promises, because that promise is
    /// the whole argument that adding `optional` did not break the wire.
    ///
    /// Three claims, each checked as bytes rather than reasoned about:
    ///
    ///   - `None` puts no field 3 on the wire, so an old daemon reading it
    ///     sees the `string` default `""` -- which is what an old client
    ///     meaning "no reason given" already sent.
    ///   - `Some("")` DOES put field 3 on the wire (tag byte `0x1a`, length
    ///     `0`), which is the difference presence buys: an implicit-presence
    ///     `string` cannot say "empty on purpose" at all.
    ///   - a plain proto3 `string` still vanishes when empty -- `actor` here,
    ///     the neighbouring field -- which is why an OLD client that sent
    ///     `reason: ""` is read as absent by a new daemon and so preserves a
    ///     reason rather than clearing it.
    ///
    /// That last one is the compatibility note worth having pinned: the
    /// upgrade makes old clients safe by default and costs them only the
    /// ability to clear a reason, which they had no way to ask for anyway.
    #[test]
    fn an_absent_block_reason_is_absent_on_the_wire_and_an_empty_one_is_not() {
        use prost::Message;

        let absent =
            v1::TaskBlockSet { reason: None, actor: String::new(), ..Default::default() };
        assert!(
            !absent.encode_to_vec().contains(&0x1au8),
            "no reason means no field 3, which an old daemon reads as the default"
        );

        let empty =
            v1::TaskBlockSet { reason: Some(String::new()), ..Default::default() };
        assert_eq!(
            empty.encode_to_vec(),
            vec![0x1a, 0x00],
            "an empty reason asked for on purpose is sent, or nobody could ever clear one"
        );

        // The neighbouring plain `string`, to show that vanishing-when-empty
        // is proto3's rule and not something this field opted into.
        let actor = v1::TaskBlockSet { actor: String::new(), ..Default::default() };
        assert!(
            actor.encode_to_vec().is_empty(),
            "an implicit-presence string is not sent when it is empty"
        );
    }

    /// Renaming a message is free on the wire only because its field numbers
    /// do not move: protobuf never sends a name. This pins every number the
    /// worktree rename touched, read by name out of the compiled descriptor,
    /// so an app built before the rename still means what it sends.
    ///
    /// Each row is (message, field, number, type). A message-typed field also
    /// pins which message sits at that number, so two renamed messages
    /// swapped between tags fail here too. The messages renamed whole are
    /// pinned field by field and must have no field the table does not name,
    /// so a field dropped or added in passing fails as well.
    #[test]
    fn renamed_messages_keep_their_field_numbers() {
        use prost::Message;
        use prost_types::FileDescriptorSet;

        let set = FileDescriptorSet::decode(
            &include_bytes!(concat!(env!("OUT_DIR"), "/farcooler_descriptor.bin"))[..],
        )
        .expect("the build writes a descriptor");
        let file = set
            .file
            .iter()
            .find(|f| f.package() == "farcooler.v1")
            .expect("farcooler.v1 is in the descriptor");
        let message = |name: &str| {
            file.message_type
                .iter()
                .find(|m| m.name() == name)
                .unwrap_or_else(|| panic!("no message {name}"))
        };

        const WT: &str = ".farcooler.v1.Worktree";
        let fields: &[(&str, &str, i32, &str)] = &[
            ("Request", "worktree_create", 23, ".farcooler.v1.WorktreeCreate"),
            ("Request", "worktree_reorder", 70, ".farcooler.v1.WorktreeReorder"),
            ("Result", "worktree", 6, WT),
            ("Result", "worktree_list", 7, ".farcooler.v1.WorktreeList"),
            ("Result", "discovered_worktree_list", 15, ".farcooler.v1.DiscoveredWorktreeList"),
            ("Event", "worktree_changed", 13, WT),
            ("Worktree", "id", 1, ""),
            ("Worktree", "resource_version", 2, ""),
            ("Worktree", "repository_id", 3, ""),
            ("Worktree", "task_name", 4, ""),
            ("Worktree", "branch", 5, ""),
            ("Worktree", "worktree_path_token", 6, ""),
            ("Worktree", "worktree_path", 7, ""),
            ("Worktree", "state", 8, ".farcooler.v1.WorktreeState"),
            ("Worktree", "is_main_checkout", 9, ""),
            ("Worktree", "ordinal", 10, ""),
            // Added after the rename by workspaces-as-workstreams, on fresh
            // tags. Listed so the whole-message check below still holds.
            ("Worktree", "workspace_id", 11, ""),
            ("Worktree", "claim_source", 12, ""),
            ("Worktree", "foreign_writer_workspace_ids", 13, ""),
            // Added by the needs-you rollup, on a fresh tag.
            ("Worktree", "open_tasks", 14, ".farcooler.v1.TaskRef"),
            // Added by ov-199, on a fresh tag.
            ("Worktree", "lfs_pointers", 15, ""),
            ("WorktreeList", "items", 1, WT),
            ("WorktreeReorder", "worktree_ids", 1, ""),
            ("WorktreeCreate", "task_name", 1, ""),
            ("WorktreeCreate", "branch", 2, ""),
            ("WorktreeCreate", "base_revision", 3, ""),
            ("WorktreeCreate", "terminal_preset", 4, ""),
            ("WorktreeCreate", "adopt_existing", 5, ""),
            ("WorktreeCreate", "fork_only", 6, ""),
            ("WorktreeCreate", "workspace_id", 7, ""),
            ("DiscoveredWorktree", "path", 1, ""),
            ("DiscoveredWorktree", "branch", 3, ""),
            ("DiscoveredWorktree", "head", 4, ""),
            ("DiscoveredWorktree", "suggested_name", 5, ""),
            ("DiscoveredWorktree", "locked", 6, ""),
            ("DiscoveredWorktreeList", "items", 1, ".farcooler.v1.DiscoveredWorktree"),
            ("InboxWorktree", "worktree_id", 1, ""),
            ("InboxWorktree", "task_name", 2, ""),
            ("InboxWorktree", "branch", 3, ""),
            ("InboxWorktree", "changed_since_reviewed", 8, ""),
            ("InboxWorktree", "insertions", 9, ""),
            ("InboxWorktree", "deletions", 10, ""),
            ("ChangesInbox", "items", 1, ".farcooler.v1.InboxWorktree"),
            ("ChangeSetSelector", "worktree", 1, ".farcooler.v1.Empty"),
            ("WorktreeFileSearch", "worktree_id", 1, ""),
            ("Terminal", "worktree_id", 4, ""),
            ("PaneGroup", "worktree_id", 2, ""),
            ("PaneGroupList", "worktree_id", 1, ""),
            ("ChangeSetRequest", "worktree_id", 1, ""),
            ("ChangeSetChanged", "worktree_id", 1, ""),
            ("ChangeSet", "worktree_id", 1, ""),
            ("CommitFilesRequest", "worktree_id", 1, ""),
            ("FileDiffRequest", "worktree_id", 1, ""),
            ("ChangesSetBase", "worktree_id", 1, ""),
            ("ChangesMarkRead", "worktree_id", 1, ""),
            ("Task", "worktree_id", 11, ""),
            ("TaskCreate", "worktree_id", 7, ""),
            ("TaskUpdate", "worktree_id", 8, ""),
        ];
        for &(m, f, number, type_name) in fields {
            let field = message(m)
                .field
                .iter()
                .find(|x| x.name() == f)
                .unwrap_or_else(|| panic!("{m} has no field {f}"));
            assert_eq!(field.number(), number, "{m}.{f} moved off tag {number}");
            if !type_name.is_empty() {
                assert_eq!(field.type_name(), type_name, "{m}.{f} carries the wrong message");
            }
        }

        // Renamed whole: every field is in the table above, so none went
        // missing and none arrived with the rename.
        for m in [
            "Worktree",
            "WorktreeList",
            "WorktreeReorder",
            "WorktreeCreate",
            "DiscoveredWorktree",
            "DiscoveredWorktreeList",
            "InboxWorktree",
        ] {
            let mut have: Vec<_> =
                message(m).field.iter().map(|x| (x.name().to_string(), x.number())).collect();
            let mut want: Vec<_> = fields
                .iter()
                .filter(|r| r.0 == m)
                .map(|r| (r.1.to_string(), r.2))
                .collect();
            have.sort();
            want.sort();
            assert_eq!(have, want, "{m} is not the message it was before the rename");
        }

        let enum_values = |name: &str| -> Vec<(String, i32)> {
            file.enum_type
                .iter()
                .find(|e| e.name() == name)
                .unwrap_or_else(|| panic!("no enum {name}"))
                .value
                .iter()
                .map(|v| (v.name().to_string(), v.number()))
                .collect()
        };
        let state: Vec<(String, i32)> = [
            ("WORKTREE_STATE_UNSPECIFIED", 0),
            ("WORKTREE_STATE_CREATING", 1),
            ("WORKTREE_STATE_READY", 2),
            ("WORKTREE_STATE_ACTIVE", 3),
            ("WORKTREE_STATE_ERROR", 4),
            ("WORKTREE_STATE_HIDDEN", 5),
            ("WORKTREE_STATE_WORKTREE_MISSING", 6),
        ]
        .map(|(n, v)| (n.to_string(), v))
        .into();
        assert_eq!(enum_values("WorktreeState"), state, "WorktreeState's numbers moved");
        assert!(
            enum_values("ErrorCode").contains(&("ERROR_CODE_WORKTREES_EXIST".to_string(), 20)),
            "ERROR_CODE_WORKTREES_EXIST moved off 20"
        );
    }

    /// The workspace additions, pinned the way the rename's numbers are
    /// above: each on a tag nothing held before, so an app built before them
    /// decodes every message exactly as it did.
    #[test]
    fn workspace_additions_take_fresh_tags() {
        use prost::Message;
        use prost_types::FileDescriptorSet;

        let set = FileDescriptorSet::decode(
            &include_bytes!(concat!(env!("OUT_DIR"), "/farcooler_descriptor.bin"))[..],
        )
        .expect("the build writes a descriptor");
        let file = set.file.iter().find(|f| f.package() == "farcooler.v1").expect("farcooler.v1");
        let number = |m: &str, f: &str| {
            file.message_type
                .iter()
                .find(|x| x.name() == m)
                .unwrap_or_else(|| panic!("no message {m}"))
                .field
                .iter()
                .find(|x| x.name() == f)
                .unwrap_or_else(|| panic!("{m} has no field {f}"))
                .number()
        };
        for (m, f, n) in [
            ("Request", "workspace_create", 80),
            ("Request", "workspace_rename", 81),
            ("Request", "workspace_set_prefix", 82),
            ("Request", "task_move", 83),
            ("Request", "worktree_assign", 84),
            ("Request", "terminal_set_role", 85),
            ("Request", "workspace_start_orchestrator", 86),
            ("Result", "workspace", 43),
            ("Result", "workspace_list", 44),
            ("Terminal", "workspace_id", 39),
            ("Terminal", "role", 40),
            ("Task", "workspace_id", 15),
            ("TaskCreate", "workspace_id", 9),
            ("TaskListRequest", "workspace_id", 4),
            ("TaskChanged", "workspace_id", 4),
            ("TaskChanged", "from_workspace_id", 5),
        ] {
            assert_eq!(number(m, f), n, "{m}.{f} moved off tag {n}");
        }
        // The last field each of these carried before, still where it was.
        assert_eq!(number("Request", "task_get_by_key"), 79);
        assert_eq!(number("Result", "task_note_hit_list"), 42);
        assert_eq!(number("Terminal", "task_id"), 37);
        assert_eq!(number("Task", "updated_at"), 14);
        assert_eq!(number("TaskChanged", "actor"), 3);
    }

    /// The needs-you additions, each on a tag nothing held before: the
    /// event after `events_missed`, the result after `workspace_list` (27 to
    /// 31 stay unused), and the worktree's tasks after its foreign writers.
    #[test]
    fn needs_you_takes_fresh_tags() {
        use prost::Message;
        use prost_types::FileDescriptorSet;

        let set = FileDescriptorSet::decode(
            &include_bytes!(concat!(env!("OUT_DIR"), "/farcooler_descriptor.bin"))[..],
        )
        .expect("the build writes a descriptor");
        let file = set.file.iter().find(|f| f.package() == "farcooler.v1").expect("farcooler.v1");
        let number = |m: &str, f: &str| {
            file.message_type
                .iter()
                .find(|x| x.name() == m)
                .unwrap_or_else(|| panic!("no message {m}"))
                .field
                .iter()
                .find(|x| x.name() == f)
                .unwrap_or_else(|| panic!("{m} has no field {f}"))
                .number()
        };
        for (m, f, n) in [
            ("Event", "needs_you_changed", 24),
            ("Result", "needs_you_list", 45),
            ("Worktree", "open_tasks", 14),
            ("Worktree", "lfs_pointers", 15),
        ] {
            assert_eq!(number(m, f), n, "{m}.{f} moved off tag {n}");
        }
        // The last field each of these carried before, still where it was.
        assert_eq!(number("Event", "events_missed"), 23);
        assert_eq!(number("Result", "workspace_list"), 44);
        assert_eq!(number("Worktree", "foreign_writer_workspace_ids"), 13);
        // And the gap in `Result` stays a gap.
        let result = file.message_type.iter().find(|x| x.name() == "Result").expect("Result");
        for n in 27..=31 {
            assert!(result.field.iter().all(|x| x.number() != n), "Result reused tag {n}");
        }
    }

    /// `report.get` on tags nothing held before: the request after
    /// `workspace_set_settings`, the result after `needs_you_list`.
    #[test]
    fn report_takes_fresh_tags() {
        use prost::Message;
        use prost_types::FileDescriptorSet;

        let set = FileDescriptorSet::decode(
            &include_bytes!(concat!(env!("OUT_DIR"), "/farcooler_descriptor.bin"))[..],
        )
        .expect("the build writes a descriptor");
        let file = set.file.iter().find(|f| f.package() == "farcooler.v1").expect("farcooler.v1");
        let number = |m: &str, f: &str| {
            file.message_type
                .iter()
                .find(|x| x.name() == m)
                .and_then(|x| x.field.iter().find(|x| x.name() == f))
                .unwrap_or_else(|| panic!("{m} has no field {f}"))
                .number()
        };
        assert_eq!(number("Request", "report_request"), 88);
        assert_eq!(number("Request", "workspace_set_settings"), 87);
        assert_eq!(number("Result", "report"), 46);
        assert_eq!(number("Result", "needs_you_list"), 45);
        assert_eq!(capability::for_method("report.get"), Some(capability::REPORT));
        assert!(capability::ALL.contains(&capability::REPORT), "the daemon would not advertise it");
    }

    /// The list is asked for by a word of its own, and the daemon
    /// advertises it: a method whose capability is missing from `ALL` is one
    /// the daemon refuses on every runner.
    #[test]
    fn needs_you_list_is_gated_on_its_own_advertised_capability() {
        assert_eq!(capability::NEEDS_YOU, "needs_you");
        assert_eq!(capability::for_method("needs_you.list"), Some(capability::NEEDS_YOU));
        assert!(capability::ALL.contains(&capability::NEEDS_YOU), "the daemon would not advertise it");
        assert_eq!(capability::STREAM_SIZE_MARKERS, "stream_size_markers");
        assert!(
            capability::ALL.contains(&capability::STREAM_SIZE_MARKERS),
            "the daemon would not advertise it"
        );
    }

    /// Terminal names and ports (ov-234) take tags nothing held before, each
    /// behind a capability of its own that the daemon advertises.
    #[test]
    fn terminal_names_and_ports_take_fresh_tags() {
        use prost::Message;
        use prost_types::FileDescriptorSet;

        let set = FileDescriptorSet::decode(
            &include_bytes!(concat!(env!("OUT_DIR"), "/farcooler_descriptor.bin"))[..],
        )
        .expect("the build writes a descriptor");
        let file = set.file.iter().find(|f| f.package() == "farcooler.v1").expect("farcooler.v1");
        let number = |m: &str, f: &str| {
            file.message_type
                .iter()
                .find(|x| x.name() == m)
                .and_then(|x| x.field.iter().find(|x| x.name() == f))
                .unwrap_or_else(|| panic!("{m} has no field {f}"))
                .number()
        };
        assert_eq!(number("Request", "terminal_rename"), 140);
        assert_eq!(number("Terminal", "ports"), 44);
        // The last field each carried before, still where it was.
        assert_eq!(number("Request", "task_worker_set"), 132);
        assert_eq!(number("Terminal", "split_of_orchestrator"), 42);
        assert_eq!(capability::for_method("terminal.rename"), Some(capability::TERMINAL_NAMES));
        for word in [capability::TERMINAL_NAMES, capability::TERMINAL_PORTS] {
            assert!(capability::ALL.contains(&word), "the daemon would not advertise {word}");
        }
    }

    /// `workspaces` already means worktrees and is frozen; workspaces as
    /// workstreams are asked for by a word of their own.
    #[test]
    fn workstreams_is_not_the_frozen_worktrees_word() {
        assert_eq!(capability::WORKTREES, "workspaces", "shipped clients ask for this word");
        assert_eq!(capability::WORKSTREAMS, "workstreams");
        assert!(capability::ALL.contains(&capability::WORKSTREAMS));
        for method in [
            "workspace.list",
            "workspace.create",
            "workspace.rename",
            "workspace.set_prefix",
            "workspace.delete",
            "task.move",
            "worktree.assign",
            "terminal.set_role",
            "workspace.start_orchestrator",
        ] {
            assert_eq!(capability::for_method(method), Some(capability::WORKSTREAMS), "{method}");
        }
    }

    /// `Terminal.notice_task_id` is a field, so no method names its capability.
    /// This is the only thing that keeps the daemon from forgetting to say it
    /// has the field, which would leave every client folding nothing.
    #[test]
    fn notice_task_is_advertised() {
        assert_eq!(capability::NOTICE_TASK, "notice_task");
        assert!(capability::ALL.contains(&capability::NOTICE_TASK), "the daemon would not advertise it");
    }

    /// Every channel, so a match arm added to one list and forgotten in another
    /// fails here rather than shipping.
    const ALL_CHANNELS: [Channel; 4] =
        [Channel::Local, Channel::Canary, Channel::Preview, Channel::Stable];

    #[test]
    fn a_channel_round_trips_through_its_name() {
        for c in ALL_CHANNELS {
            assert_eq!(Channel::from_str_or_local(c.as_str()), c);
        }
    }

    #[test]
    fn an_unknown_channel_is_local_not_stable() {
        // Defaulting the other way would let a hand-made build pass itself off
        // as a release. scripts/version.sh makes the same choice for the same
        // reason.
        assert_eq!(Channel::from_str_or_local(""), Channel::Local);
        assert_eq!(Channel::from_str_or_local("nonsense"), Channel::Local);
        assert_eq!(Channel::from_str_or_local("STABLE"), Channel::Local);
        // The names this replaced. A build stamped by an older checkout must
        // not silently land on the wrong channel — `local` is where anything
        // unreadable belongs.
        assert_eq!(Channel::from_str_or_local("release"), Channel::Local);
        assert_eq!(Channel::from_str_or_local("beta"), Channel::Local);
        assert_eq!(Channel::from_str_or_local("dev"), Channel::Local);
    }

    #[test]
    fn the_stamped_channel_is_one_of_the_four() {
        assert!(ALL_CHANNELS.contains(&CHANNEL));
    }

    /// Each method is one wire name and back again, and no two share a name.
    ///
    /// The macro writes the name into `name` and `parse` from one row, so the
    /// round trip can only fail on a duplicate: `parse` would answer the first
    /// row for both, and the second would be unreachable on the wire.
    #[test]
    fn every_method_round_trips_through_its_wire_name() {
        let names: std::collections::BTreeSet<_> = method::Method::ALL.iter().map(|m| m.name()).collect();
        assert_eq!(names.len(), method::Method::ALL.len(), "two methods share a wire name");
        for &m in method::Method::ALL {
            assert_eq!(method::Method::parse(m.name()), Some(m), "{m:?}");
            assert_eq!(capability::for_method(m.name()), Some(m.capability()), "{m:?}");
        }
        // The agent queue's three, which the daemon's own scope table was
        // missing while this table had them.
        for name in ["terminal.agent_edit_queued", "terminal.agent_cancel_queued", "terminal.agent_steer_queued"] {
            assert_eq!(capability::for_method(name), Some(capability::AGENT_QUEUE), "{name}");
        }
        // And the ones they act on stay under `agent`: an older runner has
        // both, and only the three above are missing there.
        for name in ["terminal.agent_prompt", "terminal.agent_cancel"] {
            assert_eq!(capability::for_method(name), Some(capability::AGENT), "{name}");
        }
    }

    /// A runner advertises the queue's capability, and the queue's methods are
    /// the only ones that need it.
    #[test]
    fn the_queue_capability_is_advertised_and_apart_from_agent() {
        assert!(capability::ALL.contains(&capability::AGENT_QUEUE), "the daemon would not advertise it");
        assert_ne!(capability::AGENT_QUEUE, capability::AGENT);
        assert_eq!(capability::AGENT_QUEUE, "agent_queue");
    }

    #[test]
    fn an_unknown_method_names_no_capability() {
        // What makes "this runner is too old" distinguishable from "no such
        // thing": a method nobody implements has no capability, and the daemon
        // turns that into CAPABILITY_UNSUPPORTED rather than NOT_FOUND.
        assert_eq!(capability::for_method("something.invented"), None);
        assert_eq!(capability::for_method(""), None);
        // Exact, as the daemon's scope table always was. This used to answer
        // `layout` for any name under `layout.`, so a layout verb this build
        // lacks read as a capability it has.
        assert_eq!(capability::for_method("layout.nonsense"), None);
    }

    #[test]
    fn the_floor_capabilities_are_always_present() {
        // Every daemon that has ever existed does worktrees and terminals, so
        // a client may assume them without asking. If either ever left this
        // list, every shipped client would break at once.
        assert!(capability::ALL.contains(&capability::WORKTREES));
        assert!(capability::ALL.contains(&capability::TERMINALS));
    }

    #[test]
    fn release_binaries_keep_their_bare_names() {
        // Every release client already in the field resolves
        // `~/.local/bin/farcoolerd`. A suffix here strands all of them at once,
        // and an App Store build cannot be corrected for days.
        assert_eq!(Channel::Stable.daemon_binary_name(), "farcoolerd");
        assert_eq!(Channel::Stable.cli_binary_name(), "farcooler");
        assert_eq!(Channel::Stable.tunnel_binary_name(), "farcooler-tunnel");
    }

    #[test]
    fn each_channel_has_its_own_binary_name() {
        for names in [
            ALL_CHANNELS.map(Channel::daemon_binary_name),
            ALL_CHANNELS.map(Channel::cli_binary_name),
            ALL_CHANNELS.map(Channel::tunnel_binary_name),
        ] {
            let unique: std::collections::BTreeSet<_> = names.iter().collect();
            assert_eq!(unique.len(), ALL_CHANNELS.len(), "two channels cannot share one path: {names:?}");
        }
    }

    #[test]
    fn a_lookup_prefers_this_channels_name_over_the_bare_one() {
        // The order is the whole isolation property. A `~/.local/bin` holding
        // both a stable install and a preview one holds two files, and a
        // preview client that checked the bare name first would find the
        // stable daemon sitting there and talk to it — which is precisely the
        // meeting the channels exist to prevent.
        for c in ALL_CHANNELS {
            assert_eq!(c.daemon_binary_candidates().first(), Some(&c.daemon_binary_name()));
            assert_eq!(c.cli_binary_candidates().first(), Some(&c.cli_binary_name()));
            assert_eq!(c.tunnel_binary_candidates().first(), Some(&c.tunnel_binary_name()));
        }
    }

    #[test]
    fn every_channel_also_answers_to_the_name_cargo_gives_it() {
        // `[[bin]] name = "farcoolerd"` is what a build produces whatever
        // channel stamped it, and `build-linux.sh`, `release.yml` and
        // `build-app.sh` all copy that name out of `target/` unchanged. A
        // lookup that accepted only the channel name would mean a checkout
        // stops being able to find what it just built the moment it is not
        // stable.
        for c in ALL_CHANNELS {
            assert!(c.daemon_binary_candidates().contains(&"farcoolerd"), "{c:?}");
            assert!(c.cli_binary_candidates().contains(&"farcooler"), "{c:?}");
            assert!(c.tunnel_binary_candidates().contains(&"farcooler-tunnel"), "{c:?}");
        }
    }

    #[test]
    fn stable_looks_for_exactly_one_name() {
        // Its channel name and cargo's name are the same string, and a list
        // that repeated it would make every caller do redundant work and
        // every error message list a path twice.
        assert_eq!(Channel::Stable.daemon_binary_candidates(), &["farcoolerd"]);
        assert_eq!(Channel::Stable.cli_binary_candidates(), &["farcooler"]);
        assert_eq!(Channel::Stable.tunnel_binary_candidates(), &["farcooler-tunnel"]);
    }
}
