//! Wire protocol: generated protobuf types plus length-delimited framing.
//!
//! Unix sockets and SSH stdio carry the exact same stream:
//! `envelope_length:u32` in network byte order followed by one serialized
//! `WireEnvelope`. The framing stays transport-portable.

pub mod framing;
pub mod ids;

/// Generated protobuf types.
pub mod v1 {
    // Generated by prost from proto/farcooler.proto. Its enum layouts are
    // prost's business, not ours, and there is nothing to act on here.
    #![allow(clippy::large_enum_variant)]

    include!(concat!(env!("OUT_DIR"), "/farcooler.v1.rs"));
}

pub use v1::*;

/// Protocol major version this build speaks.
pub const PROTOCOL_VERSION: u32 = 1;

/// Which source this binary was built from: `0.1.0+a1b2c3d`, `-dirty` if the
/// worktree had uncommitted changes.
///
/// Reported by the daemon in every handshake and sent by every client in its
/// own, so that two components built from different source SAY so rather than
/// disagreeing silently — which is exactly how a fixed bug goes on reproducing.
/// `PROTOCOL_VERSION` answers "can these talk"; this answers "are these the
/// same build", and they are different questions.
pub const BUILD: &str = env!("FARCOOLER_BUILD");

/// Control envelopes are capped at 1 MiB.
pub const MAX_CONTROL_ENVELOPE_BYTES: usize = 1024 * 1024;

/// `TerminalFrame.payload` is capped at 64 KiB.
pub const MAX_TERMINAL_PAYLOAD_BYTES: usize = 64 * 1024;

/// One chunk of an image being pasted into a terminal.
///
/// Twice a terminal frame and an eighth of the envelope ceiling: big enough
/// that a 16 MiB image is 128 round trips rather than a thousand, small enough
/// that live output interleaves between chunks instead of waiting behind one.
pub const IMAGE_PASTE_CHUNK_BYTES: usize = 128 * 1024;

/// The largest image a client may paste into a terminal.
///
/// Larger than any screenshot and smaller than a ProRAW photo. Checked on both
/// sides: the client refuses before uploading anything, the daemon refuses
/// before writing anything.
pub const MAX_IMAGE_PASTE_BYTES: u64 = 16 * 1024 * 1024;

/// Each terminal retains the most recent 8 MiB of its current epoch.
pub const REPLAY_BUFFER_BYTES: u64 = 8 * 1024 * 1024;

/// Per-client terminal output window: unacknowledged data cap.
pub const MAX_UNACKED_TERMINAL_BYTES: u64 = 1024 * 1024;

/// Control channel ceiling: queued unwritten control envelopes per client.
pub const MAX_QUEUED_CONTROL_BYTES: u64 = 4 * 1024 * 1024;

/// Clients acknowledge at 256 KiB unacknowledged or 250 ms, whichever first,
/// and always within 1 s of output that leaves anything unacknowledged.
pub const FLOW_ACK_BYTES_THRESHOLD: u64 = 256 * 1024;
pub const FLOW_ACK_INTERVAL_MS: u64 = 250;
pub const FLOW_ACK_MAX_DELAY_MS: u64 = 1000;

/// A disconnected writer lease expires after 30 seconds.
pub const WRITER_LEASE_EXPIRY_SECS: u64 = 30;

/// Terminal dimensions are clamped to these ranges.
pub const MIN_COLUMNS: u32 = 20;
pub const MAX_COLUMNS: u32 = 500;
pub const MIN_ROWS: u32 = 5;
pub const MAX_ROWS: u32 = 200;
