//! Claude Code's own transcript markup, resolved to what its CLI shows.
//!
//! A Claude Code transcript is not only what the user typed. The CLI wraps its
//! own bookkeeping in pseudo-XML and stores it in the same `user` records:
//!
//! ```text
//! <local-command-caveat>Caveat: The messages below were generated by the user
//! while running local commands. DO NOT respond to these messages…</local-command-caveat>
//!
//! <command-name>/model</command-name>
//!             <command-message>model</command-message>
//!             <command-args>haiku</command-args>
//!
//! <local-command-stdout>Set model to haiku (claude-haiku-4-5-20251001)</local-command-stdout>
//!
//! …the prompt the user actually typed<system-reminder>This memory is 4 days
//! old…</system-reminder>
//! ```
//!
//! Its own UI never draws any of it — a slash command shows as `/model haiku`
//! and the caveat and the reminders show as nothing at all. We drew every
//! angle bracket verbatim, so a session that had ever run a slash command read
//! as a wall of markup nobody wrote.
//!
//! What a local command PRINTED is kept — it is the answer to the command the
//! reader can see — but only after `without_ansi`, since the CLI writes it for
//! a terminal and a transcript row is not one.
//!
//! Three deliberate limits, because each is a place this could do harm:
//!
//! * **Only what the user's own record can contain.** The agent's replies are
//!   left alone. An agent that explains these tags — this file's own commit
//!   message does — must be quoted exactly, and agent text arrives a delta at a
//!   time, so a tag can straddle two chunks and a per-chunk rewrite would eat
//!   half of one. A `user` record arrives whole.
//! * **Tool output is left alone too.** `<system-reminder>` appears in tool
//!   results as well ("the file exists but the contents are empty"), and there
//!   it is telling a reader something true about the file. Hiding it would cost
//!   information rather than noise.
//! * **An unclosed tag loses the tag, not the text.** `<system-reminder>` with
//!   no closing tag could be a truncated injection or could be a person asking
//!   what the thing is. Dropping to the end of the message would silently eat a
//!   real question; dropping the four words of markup cannot.

/// Elements whose contents are the CLI talking to the model, not to a reader.
const HIDDEN: &[&str] = &["local-command-caveat", "system-reminder", "command-message"];

/// Elements that are only a wrapper: the contents are what a reader wants.
const SPOKEN: &[&str] = &["local-command-stdout", "local-command-stderr", "command-args"];

/// `<command-name>` opens the one construct that spans several elements, so it
/// is handled apart from both lists above.
const COMMAND_NAME: &str = "command-name";

/// The text with Claude Code's markup resolved.
///
/// Returns the input UNCHANGED when it contains none — which is almost every
/// message, and which is what makes this safe to put in the path of all of
/// them. Only a message that really carried markup is trimmed and rewritten.
pub fn without_harness_markup(text: &str) -> String {
    if !text.contains('<') {
        return text.to_string();
    }

    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    let mut touched = false;
    // A slash command is three elements and one line: `/model haiku`. The
    // whitespace the CLI writes between them is layout for a file, not for a
    // reader, so it is dropped while the construct is still open.
    let mut in_command = false;

    while let Some((before, name, kind, after)) = next_element(rest) {
        if in_command && before.trim().is_empty() {
            // swallowed: it is the indentation between the trio's elements
        } else {
            out.push_str(before);
            if !before.trim().is_empty() {
                in_command = false;
            }
        }
        touched = true;

        match kind {
            Element::Hidden { after_close } => {
                rest = after_close;
            }
            Element::Spoken { inner, after_close } => {
                let inner = if in_command { inner.trim() } else { inner };
                let inner = without_ansi(inner);
                if !inner.is_empty() {
                    if in_command && !out.is_empty() && !out.ends_with(char::is_whitespace) {
                        out.push(' ');
                    }
                    out.push_str(&inner);
                }
                if name == COMMAND_NAME {
                    in_command = true;
                }
                rest = after_close;
            }
            Element::Unclosed => {
                // The opening tag is gone; everything after it stays.
                rest = after;
            }
        }
    }
    out.push_str(rest);

    if !touched {
        return text.to_string();
    }
    out.trim().to_string()
}

/// A local command's output with its terminal escapes removed.
///
/// Found by running this over 1110 real transcripts: `/model` writes
/// `Set model to \x1b[1mHaiku 4.5\x1b[22m for this session only` into
/// `<local-command-stdout>`. Those bytes are an instruction to a terminal, and
/// a transcript row is not one — SwiftUI draws them as nothing or as garbage,
/// depending on the sequence. Newer versions of the CLI write `` `Haiku 4.5` ``
/// instead, so this is history rather than a moving target, but the history is
/// on disk and gets replayed.
///
/// Removed rather than translated. Turning SGR back into markdown would be
/// guessing at intent from a numeric parameter, and the sentence reads
/// correctly without any emphasis at all.
fn without_ansi(text: &str) -> String {
    if !text.contains('\u{1b}') {
        return text.to_string();
    }
    let mut out = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();
    while let Some(c) = chars.next() {
        if c != '\u{1b}' {
            out.push(c);
            continue;
        }
        // CSI: parameters and intermediates, then one final byte that ends it.
        if chars.peek() == Some(&'[') {
            chars.next();
            for c in chars.by_ref() {
                if ('\u{40}'..='\u{7e}').contains(&c) {
                    break;
                }
            }
            continue;
        }
        // Anything else introduced by an escape: the escape and the one
        // character that names it.
        chars.next();
    }
    out
}

enum Element<'a> {
    Hidden { after_close: &'a str },
    Spoken { inner: &'a str, after_close: &'a str },
    Unclosed,
}

/// The next known element in `text`: what precedes it, its name, what it is,
/// and what follows its opening tag.
fn next_element(text: &str) -> Option<(&str, &'static str, Element<'_>, &str)> {
    let mut search = 0;
    while let Some(offset) = text[search..].find('<') {
        let at = search + offset;
        let tail = &text[at..];
        let known = HIDDEN
            .iter()
            .chain(SPOKEN.iter())
            .chain(std::iter::once(&COMMAND_NAME))
            .find(|name| tail.starts_with(&format!("<{name}>")));
        let Some(name) = known else {
            search = at + 1;
            continue;
        };
        let before = &text[..at];
        let after_open = &tail[name.len() + 2..];
        let close = format!("</{name}>");
        let Some(end) = after_open.find(&close) else {
            return Some((before, name, Element::Unclosed, after_open));
        };
        let inner = &after_open[..end];
        let after_close = &after_open[end + close.len()..];
        let kind = if HIDDEN.contains(name) {
            Element::Hidden { after_close }
        } else {
            Element::Spoken { inner, after_close }
        };
        return Some((before, name, kind, after_open));
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The exact bytes of a caveat record, from a real transcript.
    const CAVEAT: &str = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>";

    #[test]
    fn ordinary_prose_is_returned_untouched() {
        let text = "Rewrite the parser so a < b renders as itself.\n\n  indented\n";
        assert_eq!(without_harness_markup(text), text);
    }

    #[test]
    fn the_caveat_leaves_nothing_behind() {
        assert_eq!(without_harness_markup(CAVEAT), "");
    }

    #[test]
    fn a_slash_command_reads_as_the_line_the_cli_shows() {
        let text = "<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args>haiku</command-args>";
        assert_eq!(without_harness_markup(text), "/model haiku");
    }

    #[test]
    fn a_slash_command_with_no_arguments_keeps_only_its_name() {
        let text = "<command-name>/plan-eng-review</command-name>";
        assert_eq!(without_harness_markup(text), "/plan-eng-review");
        let empty = "<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args></command-args>";
        assert_eq!(without_harness_markup(empty), "/model");
    }

    #[test]
    fn command_output_is_kept_without_its_wrapper() {
        let text = "<local-command-stdout>Set model to haiku (claude-haiku-4-5-20251001)</local-command-stdout>";
        assert_eq!(
            without_harness_markup(text),
            "Set model to haiku (claude-haiku-4-5-20251001)"
        );
        assert_eq!(without_harness_markup("<local-command-stdout></local-command-stdout>"), "");
    }

    /// The tag the owner saw is one of a family. A fix for the one instance
    /// would leave every other member of it on screen.
    #[test]
    fn every_tag_in_the_family_is_handled() {
        for tag in HIDDEN {
            let text = format!("before <{tag}>hidden</{tag}> after");
            assert_eq!(without_harness_markup(&text), "before  after", "{tag}");
        }
        for tag in SPOKEN {
            let text = format!("before <{tag}>kept</{tag}> after");
            assert_eq!(without_harness_markup(&text), "before kept after", "{tag}");
        }
    }

    /// What `/model` really wrote, from a transcript on this machine.
    #[test]
    fn command_output_loses_the_terminal_escapes_it_was_written_for() {
        let text = "<local-command-stdout>Set model to \u{1b}[1mHaiku 4.5\u{1b}[22m for this session only</local-command-stdout>";
        assert_eq!(
            without_harness_markup(text),
            "Set model to Haiku 4.5 for this session only"
        );
    }

    /// Escapes in the user's OWN words are not touched — nothing outside a
    /// wrapper is terminal output.
    #[test]
    fn escapes_outside_a_wrapper_are_left_alone() {
        let text = "Why does \u{1b}[1m show up?<system-reminder>x</system-reminder>";
        assert_eq!(without_harness_markup(text), "Why does \u{1b}[1m show up?");
    }

    /// Not every tag is at the end. A reminder is appended to the prompt the
    /// user typed, and a `<command-args>` sits between two others.
    #[test]
    fn a_tag_in_the_middle_takes_only_itself() {
        let text = "Look at the diff.<system-reminder>The user opened a file.</system-reminder>\n\nThen ship it.";
        assert_eq!(without_harness_markup(text), "Look at the diff.\n\nThen ship it.");
    }

    #[test]
    fn an_unclosed_tag_costs_the_tag_and_not_the_message() {
        assert_eq!(
            without_harness_markup("What does <system-reminder> mean in a transcript?"),
            "What does  mean in a transcript?"
        );
        assert_eq!(
            without_harness_markup("<local-command-caveat>Caveat: The messages below"),
            "Caveat: The messages below"
        );
    }

    /// Markup this does not know is not markup. A prompt is allowed to contain
    /// angle brackets, and generics and HTML are the common case.
    #[test]
    fn unknown_tags_survive() {
        let text = "Use <div> here, and Vec<String> there, and <system-reminders> is not a tag.";
        assert_eq!(without_harness_markup(text), text);
    }

    #[test]
    fn several_elements_in_one_message_are_all_taken() {
        let text = format!("{CAVEAT}\n<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args>haiku</command-args>");
        assert_eq!(without_harness_markup(&text), "/model haiku");
    }

    /// Running it twice must not say something different from running it once —
    /// the same text is normalized on the live path and again on replay.
    #[test]
    fn it_is_idempotent() {
        for text in [
            CAVEAT,
            "<command-name>/model</command-name>\n <command-args>haiku</command-args>",
            "Look at <system-reminder>x</system-reminder> this",
            "plain prose",
        ] {
            let once = without_harness_markup(text);
            assert_eq!(without_harness_markup(&once), once, "{text}");
        }
    }
}
