#!/usr/bin/env python3
"""Generate the capability names the phones and the Mac ask for by.

`farcooler_protocol::capability` (crates/protocol/src/lib.rs) is the one table
of what a runner can do, by name. The apps used to spell each name by hand in
`can("...")`, so a misspelling compiled and read as "this runner can't": the
control dimmed, with nothing said anywhere. This script writes a Swift and a
Kotlin enum from the table, and `can` takes the enum, so a name the table
doesn't have is a compile error on both phones.

The identifier follows the Rust constant, not the wire value, so a caller
writes the word the Rust code uses. `Capability.worktrees` is the wire word
"workspaces": the value kept its old spelling because shipped clients ask for
it, and the trap of a name that differs from its value is now in one place.

    scripts/capability-names.py            # rewrite the generated files
    scripts/capability-names.py --check    # fail if they are out of date (CI)
    scripts/capability-names.py --self-test
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUST = ROOT / "crates/protocol/src/lib.rs"
SWIFT = ROOT / "apps/shared/AgentKit/Sources/AgentKit/Capability.swift"
KOTLIN = ROOT / "apps/android/app/src/main/java/com/farcooler/model/Capability.kt"

CONST = re.compile(r'^\s*pub const ([A-Z][A-Z0-9_]*): &str = "([a-z_]+)";', re.M)


def module_body(source):
    """The text of `pub mod capability { ... }`, found by brace matching."""
    start = source.index("pub mod capability {")
    depth = 0
    for i in range(source.index("{", start), len(source)):
        depth += {"{": 1, "}": -1}.get(source[i], 0)
        if depth == 0:
            return source[start : i + 1]
    raise SystemExit("capability module is not closed")


def read_table(source):
    """[(RUST_NAME, wire value)] in declaration order, checked against ALL."""
    body = module_body(source)
    names = CONST.findall(body)
    all_match = re.search(r"pub const ALL: &\[&str\] =\s*&\[(.*?)\];", body, re.S)
    if not all_match:
        raise SystemExit("capability::ALL not found")
    listed = [w for w in re.findall(r"[A-Z][A-Z0-9_]*", all_match.group(1))]
    declared = [n for n, _ in names]
    if sorted(listed) != sorted(declared):
        raise SystemExit(f"capability::ALL and the constants differ: {sorted(set(listed) ^ set(declared))}")
    values = [v for _, v in names]
    if len(set(values)) != len(values):
        raise SystemExit("two capability constants share a wire value")
    return names


def camel(name):
    head, *rest = name.lower().split("_")
    return head + "".join(p.capitalize() for p in rest)


def swift(table):
    lines = [
        "// GENERATED by scripts/capability-names.py from `farcooler_protocol::capability`",
        "// (crates/protocol/src/lib.rs). Do not edit; CI fails when it is out of date.",
        "",
        "/// What a runner can do, by name: one case per `farcooler_protocol::capability`",
        "/// constant. The case follows the Rust constant's name and the raw value is the",
        "/// wire word, which is not always the same: `worktrees` is \"workspaces\".",
        "public enum Capability: String, CaseIterable, Sendable {",
    ]
    lines += [f'    case {camel(n)} = "{v}"' for n, v in table]
    lines += ["}", ""]
    return "\n".join(lines)


def kotlin(table):
    lines = [
        "// GENERATED by scripts/capability-names.py from `farcooler_protocol::capability`",
        "// (crates/protocol/src/lib.rs). Do not edit; CI fails when it is out of date.",
        "package com.farcooler.model",
        "",
        "/**",
        " * What a runner can do, by name: one entry per `farcooler_protocol::capability`",
        " * constant. The entry follows the Rust constant's name and [wire] is the wire",
        " * word, which is not always the same: `WORKTREES` is \"workspaces\".",
        " */",
        "enum class Capability(val wire: String) {",
    ]
    for i, (n, v) in enumerate(table):
        lines.append(f'    {n}("{v}")' + ("," if i < len(table) - 1 else ";"))
    lines += ["}", ""]
    return "\n".join(lines)


def outputs(source):
    table = read_table(source)
    return {SWIFT: swift(table), KOTLIN: kotlin(table)}


def self_test():
    src = 'pub mod capability {\n pub const A_B: &str = "a_b";\n pub const C: &str = "x";\n pub const ALL: &[&str] = &[A_B, C];\n}'
    assert read_table(src) == [("A_B", "a_b"), ("C", "x")]
    assert 'case aB = "a_b"' in swift(read_table(src))
    assert 'A_B("a_b"),' in kotlin(read_table(src)) and 'C("x");' in kotlin(read_table(src))
    try:
        read_table(src.replace("[A_B, C]", "[A_B]"))
    except SystemExit:
        pass
    else:
        raise AssertionError("a constant missing from ALL must fail")
    real = read_table(RUST.read_text())
    assert ("WORKTREES", "workspaces") in real
    print("self-test ok")


def main():
    if "--self-test" in sys.argv:
        return self_test()
    stale = []
    for path, text in outputs(RUST.read_text()).items():
        if "--check" in sys.argv:
            if not path.exists() or path.read_text() != text:
                stale.append(path.relative_to(ROOT))
        else:
            path.write_text(text)
    if stale:
        print("out of date, run scripts/capability-names.py: " + ", ".join(map(str, stale)))
        sys.exit(1)


if __name__ == "__main__":
    main()
