[package]
name = "farcooler-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
bytes.workspace = true
thiserror.workspace = true
uuid.workspace = true

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored.workspace = true
