[package]
name = "farcooler-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
farcooler-core.workspace = true
farcooler-protocol.workspace = true
rusqlite.workspace = true
uuid.workspace = true
thiserror.workspace = true
tracing.workspace = true
